version: "3.8"

services:
  app:
    container_name: express-mia
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    env_file:
      - .env.production
    restart: always
