version: "3.8"

services:
  app:
    container_name: express-mia
    build: .
    network_mode: "host" # Pastikan Docker bisa akses jaringan host langsung
    environment:
      DATABASE_HOST: localhost
      DATABASE_USER: adminpanel_chatbot
      DATABASE_PASSWORD: 4FDICxDkeuuT
      DATABASE_NAME: adminpanel_chatbot
    ports:
      - "3030:3030"
    restart: always
